### ISSUE TITLE
Memory Problems with imagine/imagine's ExifMetaDataReader

### ISSUE THREAD

**Issue by rothfahl** [netgen/ezpublish-kernel#53]
`BinaryLoader->find($path)` (https://github.com/netgen/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishCoreBundle/Imagine/BinaryLoader.php#L42) returns an `Liip\ImagineBundle\Model\Binary`even if $path is a local path.

That makes the `ExifMetadataReader` of the underlying imagine/imagine library treat it as a binary stream (https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Image/Metadata/ExifMetadataReader.php#L39). As a result, the file gets read into a binary-string again, just to extract the Exif-Data.

A possible fix would be, not to return a `Liip\ImagineBundle\Model\Binary` from `BinaryLoader` but a `Liip\ImagineBundle\Model\FileBinary` instead, if `$path` references a local file. I'd like to create a PR, but I don't know the ezpublish-kernel enough to estimate the consequences of such a change. Any thoughts?

**Comment by emodric** [comment]
Hi @rothfahl !

The issue should definitely be opened against the original ezpublish-kernel repo (https://github.com/ezsystems/ezpublish-kernel), because that's the origin of the problem and authors of the said code will probably know more and know how to answer your question.

This repo is just a fork to maintain an older version of the kernel for bugfixes.

**Comment by rothfahl** [comment]
Hi @emodric  

Ok, thnx a lot! I'll open an issue in ezsystems issue tracker.

**Comment by emodric** [comment]
Great :)

Once the issue is fixed over there, we can port it here if it is simple enough.
